version: '3'

services:
  php:
    container_name: fasttrack_symfony5_php
    build: ./docker/php
    volumes:
      - ./www:/var/www
    links:
      - database
    environment:
      TZ: Asia/Tokyo

  nginx:
    container_name: fasttrack_symfony5_nginx
    image: nginx:latest
    ports:
      - 85:80
    volumes:
      - ./www:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    environment:
      TZ: Asia/Tokyo

  database:
    container_name: fasttrack_symfony5_pgsqld
    image: postgres:latest
    ports:
      - "54321:5432"
    volumes:
      - pgsql_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: symfony_user
      POSTGRES_PASSWORD: secret

  redis:
    container_name: fasttrack_symfony5_redis
    image: redis:latest
    command: redis-server --appendonly yes --requirepass secret
    environment:
      TZ: Asia/Tokyo

volumes:
  pgsql_data:
    driver: local